### ISSUE TITLE
Question: does this package automatically handle abiding by rate limits

### ISSUE THREAD

**Issue by Tiger-I-Yang** [vartanbeno/go-reddit#47]
if I were to spam call subreddit.NewPosts(), will the method just block as nessecary to skirt just under reddit's rate limit, or will it just return any rate limit errors

**Comment by sesopenko** [comment]
Looking at the source code, no it doesn't.   In any given `Response` object returned by one of the client services, you can check the [Rate](https://pkg.go.dev/github.com/vartanbeno/go-reddit/v2/reddit#Rate) object to see if there's rate limit remaining.

When the library makes an api call, if reddit has a response header stating there's no rate limit left, the library will return a [RateLimitError](https://pkg.go.dev/github.com/vartanbeno/go-reddit/v2/reddit#RateLimitError) and you'll have to implement your own throttling logic to handle that.

Unfortunately, the library will return a `RateLimmitError` if there's no rate limit left, even if the request was fulfilled by reddit (ie: you used your last api call left for the 10 minute period).  It won't return with a populated result in this case.  [See source code here](https://github.com/vartanbeno/go-reddit/blob/master/reddit/reddit.go#L366)

If CheckResponse returns a rate limit error, it short circuits out and doesn't build the actual response from the body, which is a bug in my opinion.

I'm investigating other libraries to see if there's something out there with more robust rate limit handling.

**Comment by Tiger-I-Yang** [comment]
I see, thanks!

**Comment by Tiger-I-Yang** [comment]
a
