### ISSUE TITLE
Push release

### ISSUE THREAD

**Issue by LordRusk** [vartanbeno/go-reddit#6]
It seems that go-reddit has progressed a lot since version 1.0.0, which is the version automatically downloaded when using go modules. Could you push another release? It has been over a 100 commits since 1.0.0 was release.

**Comment by vartanbeno** [comment]
Hey! Yep, I've been meaning to do so. I'll take some time this weekend to go over everything, create a change log, and tag a new release.

**Comment by LordRusk** [comment]
Thank you!

**Comment by vartanbeno** [comment]
Hey! I just tagged a new release, [v2.0.0](https://github.com/vartanbeno/go-reddit/releases/tag/v2.0.0).
