### ISSUE TITLE
REQUEST: Add a "projects using go-reddit" section

### ISSUE THREAD

**Issue by xxxserxxx** [vartanbeno/go-reddit#7]
I know of no easy way to find projects *using* other projects; it'd be neat to have a list -- even if not comprehensive -- of utilities using this library.  Maybe you could open a wiki page and accept PRs against a project list?

**Comment by vartanbeno** [comment]
I think this is a great idea, but at the current state of the package, I don't think there are enough projects out there using it to justify having a section like this. I'd definitely consider it in the future though!

For now, [here](https://pkg.go.dev/github.com/vartanbeno/go-reddit/reddit?tab=importedby) is a page indicating which projects import my package.
