### ISSUE TITLE
godoc shows v1.0.0 as latest version.

### ISSUE THREAD

**Issue by LordRusk** [vartanbeno/go-reddit#8]
Seems as though the [godoc](https://pkg.go.dev/github.com/vartanbeno/go-reddit/) shows the latest version as v1.0.0. Is there a way to fix this?

**Comment by vartanbeno** [comment]
Hey! Thanks for opening this issue. It led me down a rabbit hole and I realized I didn't follow the major version strategy of including `/v2` in the module path. It should be good now
